name: Release

on:
  push:
    # tags:
    #   - "v*"

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mpv (macOS)
        run: brew install mpv

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build macOS binaries
        env:
          CGO_ENABLED: 1
          CGO_CFLAGS: "-I$(brew --prefix mpv)/include"
          CGO_LDFLAGS: "-L$(brew --prefix mpv)/lib -lmpv"
        run: |
          export C_INCLUDE_PATH=/opt/homebrew/include:$C_INCLUDE_PATH
          export LIBRARY_PATH=/opt/homebrew/lib:$LIBRARY_PATH
          GOOS=darwin GOARCH=arm64 go build -o navicli-darwin-arm64 .
          tar -czvf macos-binaries.tar.gz navicli-darwin-*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release.tar.gz
          body: "## Changelog\n\n- Feature 1\n- Bug fix 2"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
